package com.haulmont.testtask;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;


/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends AbsoluteLayout {
    protected HorizontalLayout horizontTopGrids;
    protected Grid gridMechanics;
    protected Grid gridClients;
    protected Button buttonDeleteClient;
    protected Button buttinAddClient;
    protected Button buttonEditClient;
    protected Button buttonEditMechanic;
    protected Button buttonDeleteMechanic;
    protected Button buttonAddMechanic;

    public MainDesign() {
        com.vaadin.ui.declarative.Design.read(this);
    }
}